#服务器
server:
  port: 8081



#mybatis配置
mybatis:
  typeAliasesPackage: com.example.simplemybatis.modules.entity
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:/mybatis-config.xml